<?php namespace ProcessWire;

class TableColumnRequired extends WireData implements Module {

	/**
	 * Module information
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Table Column Required',
			'summary' => 'Adds a "required" option for columns within ProFields Table.',
			'version' => '0.1.2',
			'author' => 'Robin Sallis',
			'href' => 'https://github.com/Toutouwai/TableColumnRequired',
			'icon' => 'asterisk',
			'autoload' => 'template=admin',
			'requires' => 'ProcessWire>=3.0.0, PHP>=5.4.0, FieldtypeTable',
		);
	}

	/**
	 * Ready
	 */
	public function ready() {
		$this->addHookAfter('Field::getInputfield', $this, 'afterGetInputfield');
		$this->addHookAfter('InputfieldTable::renderCol', $this, 'afterRenderCol');
		$this->addHookAfter('InputfieldTable::renderReadyHook', $this, 'afterRenderReady');
		$this->addHookAfter('InputfieldTable::processInput', $this, 'afterProcessInput');
		$this->addHookAfter('FieldtypeTable::getConfigInputfields', $this, 'addConfig');
		$this->addHookAfter('FieldtypeTable::getConfigAllowContext', $this, 'allowContext');
	}

	/**
	 * After Field::getInputfield
	 *
	 * @param HookEvent $event
	 */
	protected function afterGetInputfield(HookEvent $event) {
		/** @var Field $field */
		$field = $event->object;
		// Only for Table fields
		if($field->type != 'FieldtypeTable') return;
		// Only for ProcessPageEdit and similar
		if(!$this->wire()->process instanceof WirePageEditor) return;
		// Only if there is at least one required column
		if(!$field->required_columns) return;

		// Get column info for required columns
		$columns = $field->type->getColumnsByName($field);

		// Add asterisk to column label
		foreach($field->required_columns as $column_name) {
			$key = 'col' . $columns[$column_name]['n'] . 'label';
			if(substr($field->$key, -1) !== '*') $field->$key .= '*';
		}
	}

	/**
	 * After InputfieldTable::renderReadyHook
	 *
	 * @param HookEvent $event
	 */
	protected function afterRenderReady(HookEvent $event) {
		/** @var InputfieldTable $inputfield */
		$inputfield = $event->object;
		$field = $inputfield->hasField;
		// Only if there is at least one required column
		if(!$field->required_columns) return;
		$session = $this->wire()->session;

		// Get any error data from session and clear
		$errors = $session->getFor($this, "tcr_errors_$inputfield->name");
		if(!$errors) return;
		$session->removeFor($this, "tcr_errors_$inputfield->name");

		// Send error data to JS
		$key = $inputfield->name;
		$inputfield->wrapAttr('data-tcr-key', $key);
		$json = wireEncodeJSON($errors);
		$inputfield->appendMarkup = <<<EOT
<script>
ProcessWire.config.TableColumnRequired.$key = $json;
</script>
EOT;

		// Add assets
		$config = $this->wire()->config;
		$config->js($this->className, $errors);
		$info = $this->getModuleInfo();
		$version = $info['version'];
		$config->styles->add($config->urls->$this . "$this.css?v=$version");
		$config->scripts->add($config->urls->$this . "$this.js?v=$version");
	}

	/**
	 * After InputfieldTable::renderCol
	 *
	 * @param HookEvent $event
	 */
	protected function afterRenderCol(HookEvent $event) {
		/** @var InputfieldTable $inputfield */
		$inputfield = $event->object;
		$field = $inputfield->hasField;
		// Only if there is at least one required column
		if(!$field->required_columns) return;
		// Wrap the column markup so the column name can be identified by class
		$col = $event->arguments(0);
		$event->return = "<div class='col-{$col['name']}'>$event->return</div>";
	}

	/**
	 * After InputfieldTable::processInput
	 *
	 * @param HookEvent $event
	 */
	protected function afterProcessInput(HookEvent $event) {
		/** @var InputfieldTable $inputfield */
		$inputfield = $event->object;
		$input = $event->arguments(0);
		$field = $inputfield->hasField;
		// Only if there is at least one required column
		if(!$field->required_columns) return;

		// Loop over input data to check for empty required columns
		$errors = [];
		$row_num = 0;
		$last_id_raw = $this->wire()->database->query("SELECT data FROM field_$field->name ORDER BY data DESC LIMIT 1")->fetchAll(\PDO::FETCH_COLUMN);
		$last_id = $last_id_raw ? reset($last_id_raw) : null;
		do {
			$row_num++;
			$id_name = $inputfield->name . "_{$row_num}__id";
			$id = $input->$id_name;
			if(is_null($id)) break;
			$id = (int) $id;
			$delete_name = $inputfield->name . "_{$row_num}__delete";
			$delete = (int) $input->$delete_name;
			if($delete) continue;
			// If this is a new row, try and work out the likely id by incrementing the last id from the DB table
			if(!$id && $last_id) {
				$last_id++;
				$id = $last_id;
			}
			$empty_columns = [];
			foreach($field->required_columns as $column_name) {
				$name_attr = $inputfield->name . "_{$row_num}_{$column_name}";
				$value = $input->$name_attr;
				if(!$value) $empty_columns[] = $column_name;
			}
			if($empty_columns) {
				$errors[] = [
					'id' => $id,
					'columns' => $empty_columns,
				];
			}
		} while(1);
		$this->wire()->session->setFor($this, "tcr_errors_$inputfield->name", $errors);

		// Show error message
		$error_count = count($errors);
		if($error_count) {
			$column_label = $this->_n('column', 'columns', count($field->required_columns));
			$row_label = $this->_n('row is', 'rows are', $error_count);
			$error_message = sprintf($this->_("%d %s missing values in required %s"), $error_count, $row_label, $column_label);
			$inputfield->error($error_message);
		}
	}

	/**
	 * Add config field
	 *
	 * @param HookEvent $event
	 */
	protected function addConfig(HookEvent $event) {
		$field = $event->arguments(0);
		/** @var InputfieldWrapper $wrapper */
		$wrapper = $event->return;
		$modules = $this->wire()->modules;

		/* @var InputfieldAsmSelect $f */
		$f = $modules->get('InputfieldAsmSelect');
		$f_name = 'required_columns';
		$f->name = $f_name;
		$f->label = $this->_('Required columns');
		$f->addOptions(array_keys($field->type->getColumnsByName($field)), false);
		$f->icon = 'asterisk';
		$f->value = $field->$f_name;
		if(!$f->value) $f->collapsed = Inputfield::collapsedYes;

		// Add field to last fieldset - not sure if fieldset was always present so fall back to wrapper when needed
		$last_inputfield = $wrapper->children->last();
		if($last_inputfield->className === 'InputfieldFieldset') {
			$last_inputfield->add($f);
		} else {
			$wrapper->add($f);
		}
	}

	/**
	 * Allow setting config field in template context
	 *
	 * @param HookEvent $event
	 */
	protected function allowContext(HookEvent $event) {
		$allowed = $event->return;
		$allowed[] = 'required_columns';
		$event->return = $allowed;
	}

}
